name: CI

on:
    push:
        branches: ["main"]
        pull_request:
            branches: ["main"]

jobs:
    api-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install API dependencies
              run: cd api && npm i
            - name: Run API tests
              run: cd api && npm run test
    client-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install client dependencies
              run: cd client && npm i
            - name: Run client tests
              run: cd client && npm run test
